Base motor
RobomasterOwltech/owlware pull request #2
Opened 2024-11-09 18:06 UTC by sofiaariasv2002

virtual void actuateVelocity(int16_t ref);
        virtual void actuatePosition(int16_t ref);
        virtual void actuateTorque(int16_t ref);

        void setVelocity();
        void setTorque();
        void setPosition(); 

esto para que se usa?

2024-11-11 20:54 UTC, JorgePerC commented
Si te refieres al set velocity/torque/pos, no sé qué hace ahí
En teoría no se ocupa xq ya tienes el actuate, que ese setea tu referencia

2024-11-11 20:58 UTC, JorgePerC requested changes

2024-11-11 20:58 UTC, JorgePerC commented on src/IntfMotor.cpp
> +        controller->velocity(ref);
El controller no tiene el método velocity
estas segura que estás llamando la cosa corecta?

2024-11-11 21:28 UTC, sofiaariasv2002 commented on src/IntfMotor.cpp
> +        controller->velocity(ref);
Lo deje porque segun yo eso va a ser polimorfismo que viene desde la clase de controller pero como ni esta la clase, por eso lo deje asi, ya que erick lo haga le cambio el metodo.

2024-11-11 21:30 UTC, JorgePerC commented on src/IntfMotor.cpp
> +        controller->velocity(ref);
Hmm... oks... y entonces xq tienes a los actuate velocity/torque/pos???
Xq me estás diciendo que es parte del controller implementarlo

2024-11-11 21:42 UTC, sofiaariasv2002 commented on src/IntfMotor.cpp
> +        controller->velocity(ref);
Para que el codigo sea mas manejable y poder crecerlo entonces se tienen que ir los actuate?

2024-11-11 21:43 UTC, JorgePerC commented on src/IntfMotor.cpp
> +        controller->velocity(ref);
Requerda que un motor no está compuesto de un sólo actuador, sino también de un sensor que te de feedback... 
Y la clase de controller, representa tu actuador...

2024-11-11 21:46 UTC, sofiaariasv2002 commented on src/IntfMotor.cpp
> +        controller->velocity(ref);
no entendi :(
el feedback es el del encoder? pero en eso ya te estas metiendo en control

2024-11-11 21:49 UTC, JorgePerC commented on src/IntfMotor.cpp
> +        controller->velocity(ref);
Un motor está compuesto de dos cosas, un actuador y un sensor. El controller es tu actuador. Te/Nos falta lo del encoder, pero esto está virtual en el feedback, xq crear un objeto para el sensor, sí los vuelve redundantes. 

Estoy de acuerdo en que setTorque/velocity/pos es innecesario, xq ya tienes un método que hace eso... 
Pero... entonces xq tenemos un actuate?

2024-11-11 21:54 UTC, sofiaariasv2002 commented on src/IntfMotor.cpp
> +        controller->velocity(ref);
para decirle al motor si esta trabajando con torque, pos o vel

2024-11-11 21:55 UTC, JorgePerC commented on src/IntfMotor.cpp
> +        controller->velocity(ref);
Yes, y si es una _interfaz_, entonces a qué metodos debe llamar??

2024-11-11 21:56 UTC, sofiaariasv2002 commented on src/IntfMotor.cpp
> +        controller->velocity(ref);
al actuate()

2024-11-11 21:58 UTC, JorgePerC commented on src/IntfMotor.cpp
> +        controller->velocity(ref);
Exacto, todo lo externo llama al actuate(), y el actuate a quién llama? Bajo principios de encapsulamiento?

2024-11-11 22:01 UTC, sofiaariasv2002 commented on src/IntfMotor.cpp
> +        controller->velocity(ref);
a los actuateVelocity? y todos eso

2024-11-11 22:06 UTC, JorgePerC commented on src/IntfMotor.cpp
> +        controller->velocity(ref);
🥳

2024-11-11 22:06 UTC, sofiaariasv2002 commented on src/IntfMotor.cpp
> +        controller->velocity(ref);
mmm llamaria ala clase del controller

2024-11-11 22:30 UTC, JorgePerC commented on inc/IntfMotor.hpp
> +        int8_t Direction;
xq direction es mayúscula 
Separa las declaración, para que sea más fácil leer las que están relacionadas

2024-11-11 22:31 UTC, JorgePerC commented on inc/IntfMotor.hpp
> +        uint8_t ID;
xq id es mayúscula

2024-11-11 22:31 UTC, JorgePerC commented on inc/IntfMotor.hpp
> +        int16_t ref;
qué es ref

2024-11-11 22:32 UTC, JorgePerC commented on inc/IntfMotor.hpp
> +        uint8_t dir;
A chinga, tiene gemelos o k

2024-11-12 00:10 UTC, JorgePerC requested changes

2024-11-12 00:10 UTC, JorgePerC commented on src/IntfMotor.cpp
> +        controller->velocity(ref);
Toda esta charla. fue ignorada en el commit 😕

2024-11-12 00:10 UTC, JorgePerC commented on inc/IntfMotor.hpp
> +        virtual float getFeedback()=0;
Ups 🙈

2024-11-12 00:10 UTC, JorgePerC commented on src/IntfMotor.cpp
> +        controller->torque(ref);
Qué pasó con los breaks

2024-11-12 00:10 UTC, JorgePerC commented on src/IntfMotor.cpp
> +void setVelocity();
Si no se ocupa, bórralo

2024-11-13 20:35 UTC, JorgePerC requested changes
Tienes un typo en una función, ya sólo falta eso

2024-11-19 13:37 UTC, JorgePerC approved these changes
Seems good to me

2024-11-19 13:39 UTC, merged